name: Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or commit SHA'
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Determine image tag
        id: meta
        run: |
          if echo "${{ inputs.ref }}" | grep -qE '^v[0-9]+.*-prn\.'; then
            echo "image_tag=${{ inputs.ref }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=snapshot" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: Build and push
        uses: ./.github/actions/build-test-push
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ steps.meta.outputs.image_tag }}
          platform: linux/amd64
