name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Determine image tag
        id: meta
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "image_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=snapshot" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v5

      - name: Build and push
        uses: ./.github/actions/build-test-push
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ steps.meta.outputs.image_tag }}
          platform: linux/amd64
